ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/io
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += adp1660.o
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm_led_torch.o
