ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
