# Legacy camera_v2 stack sourced from LNX.LA.3.5.1-10610-8x26.0
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/codecs
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/isps
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/pproc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/jpeg_10

obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm.o
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += camera/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm_vb2/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += sensor/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += isp/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += ispif/
obj-$(CONFIG_MSMB_JPEG) += jpeg_10/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += msm_buf_mgr/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += pproc/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += gemini/
